import{useEffect,useState}from'react';import{api}from'../services/api';import{Save,FileText}from'lucide-react';export default function ReportsPage(){const[cases,setCases]=useState<any[]>([]);const[caseId,setCaseId]=useState('');const[reports,setReports]=useState<any[]>([]);const[title,setTitle]=useState('Investigation report');const[content,setContent]=useState('');const[id,setId]=useState<string|null>(null);useEffect(()=>{api.get('/cases').then(r=>{setCases(r.data);if(r.data[0])setCaseId(r.data[0].id)})},[]);useEffect(()=>{if(!caseId)return;api.get('/reports',{params:{caseId}}).then(r=>{setReports(r.data);if(r.data[0]){setId(r.data[0].id);setTitle(r.data[0].title);setContent(r.data[0].content)}})},[caseId]);const save=async()=>{if(id)await api.put('/reports/'+id,{title,content});else{const r=await api.post('/reports',{caseId,title,content});setId(r.data.id)};const r=await api.get('/reports',{params:{caseId}});setReports(r.data)};const pick=(r:any)=>{setId(r.id);setTitle(r.title);setContent(r.content)};return <div><div className="page-head"><div><div className="eyebrow">REPORTING</div><h1>Investigation reports</h1><p>Write, save and maintain case reports from verified case records.</p></div><button className="primary" onClick={save}><Save size={15}/> Save draft</button></div><div className="report-layout"><aside className="panel report-list"><h2>Reports</h2>{reports.map(r=><button key={r.id} className={'report-item '+(id===r.id?'selected':'')} onClick={()=>pick(r)}><FileText size={15}/><span>{r.title}<small>{r.status} · {new Date(r.updatedAt).toLocaleDateString()}</small></span></button>)}{!reports.length&&<div className="empty">No reports yet.</div>}</aside><section className="panel report-editor"><label>Case<select value={caseId} onChange={e=>setCaseId(e.target.value)}>{cases.map(c=><option key={c.id} value={c.id}>{c.caseNumber} · {c.title}</option>)}</select></label><label>Report title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Content<textarea className="report-text" value={content} onChange={e=>setContent(e.target.value)} placeholder="Executive summary

Evidence and source references

Key relationships

Findings

Recommendations"/></label></section></div></div>}
